language: php
matrix:
    include:
      - php: '5.5'
        env: BEHAT_TAGS=~@php70
      - php: '5.6'
        env: BEHAT_TAGS=~@php70
      - php: '7.0'
        env: BEHAT_TAGS=~@
install:
    - composer install
script: bin/peridot specs/ && bin/behat --tags $BEHAT_TAGS --colors
